version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/Segment/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"

  - package-ecosystem: "npm"
    directory: "/App"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"

  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"
