---
- name: Setup
  hosts: tag_Name_outfits_ai
  become: true
  gather_facts: yes
  vars_files:
    - aws_credentials.yml
  vars:
    env_file_path: "/home/ec2-user/.env"
  tasks:
    - name: Update system packages
      yum:
        name: "*"
        state: latest

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Add the current user to the docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Download Docker Compose binary
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: "0755"

    - name: Create a symlink for docker-compose
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link

    - name: Copy ENV file
      copy:
        src: ../../.env
        dest: /home/ec2-user

    - name: Copy Compose file
      copy:
        src: ../../compose.yml
        dest: /home/ec2-user/compose.yaml

    - name: Copy Script file
      copy:
        src: ../../ip.sh
        dest: /home/ec2-user/

    - name: Run the Script
      command: sh ip.sh

    - name: Check for Latest Update
      command: sudo docker-compose pull
    - name: Start Applications
      command: sudo docker-compose --env-file ./.env up -d
