import { create } from "zustand";
import { Product } from "../types/types"; // Import unified Product interface

interface ExploreState {
  products: Product[];
  addProduct: (product: Product) => void;
  removeProduct: (id: string) => void;
}

export const useExploreStore = create<ExploreState>((set) => ({
  products: [
    {
      id: "1",
      title: "HRX Training Jacket",
      description: "High-performance jacket for active wear.",
      brand: "HRX",
      category: "Jackets",
      price: 758,
      currency: "INR",
      discountPercentage: 67,
      images: ["https://via.placeholder.com/300"],
      availableColors: ["#000000", "#FFFFFF"],
      availableSizes: ["S", "M", "L"],
      material: "Polyester",
      fit: "Regular",
      style: "Athleisure",
      rating: 4.2,
      totalReviews: 152,
      seller: "HRX Official",
      deliveryTime: "2-5 days",
      returnPolicy: "10-day return",
    },
    {
      id: "2",
      title: "Adidas Sports T-Shirt",
      description: "Lightweight and breathable sports tee.",
      brand: "Adidas",
      category: "T-Shirts",
      price: 999,
      currency: "INR",
      discountPercentage: 50,
      images: ["https://via.placeholder.com/300"],
      availableColors: ["#FF0000", "#00FF00"],
      availableSizes: ["S", "M", "L", "XL"],
      material: "Cotton Blend",
      fit: "Slim",
      style: "Sportswear",
      rating: 4.5,
      totalReviews: 320,
      seller: "Adidas India",
      deliveryTime: "3-7 days",
      returnPolicy: "10-day return",
    },
    {
      id: "3",
      title: "Nike Running Shoes",
      description: "Cushioned and durable running shoes for long-distance runners.",
      brand: "Nike",
      category: "Shoes",
      price: 3499,
      currency: "INR",
      discountPercentage: 30,
      images: ["https://via.placeholder.com/300"],
      availableColors: ["#111111", "#FF5733"],
      availableSizes: ["6", "7", "8", "9", "10"],
      material: "Mesh",
      fit: "True to size",
      style: "Running",
      rating: 4.7,
      totalReviews: 500,
      seller: "Nike Official",
      deliveryTime: "3-5 days",
      returnPolicy: "15-day return",
    },
    {
      id: "4",
      title: "Levi’s Denim Jacket",
      description: "Classic fit denim jacket for casual wear.",
      brand: "Levi's",
      category: "Jackets",
      price: 2999,
      currency: "INR",
      discountPercentage: 40,
      images: ["https://via.placeholder.com/300"],
      availableColors: ["#1A1A1A", "#3D3D3D"],
      availableSizes: ["M", "L", "XL"],
      material: "Denim",
      fit: "Classic",
      style: "Casual",
      rating: 4.4,
      totalReviews: 210,
      seller: "Levi’s Official Store",
      deliveryTime: "4-6 days",
      returnPolicy: "10-day return",
    },
    {
      id: "5",
      title: "Puma Training Shorts",
      description: "Lightweight shorts with sweat-wicking fabric.",
      brand: "Puma",
      category: "Accessories",
      price: 1299,
      currency: "INR",
      discountPercentage: 35,
      images: ["https://via.placeholder.com/300"],
      availableColors: ["#222222", "#AAAAAA"],
      availableSizes: ["S", "M", "L", "XL"],
      material: "Polyester",
      fit: "Regular",
      style: "Athletic",
      rating: 4.1,
      totalReviews: 98,
      seller: "Puma Official",
      deliveryTime: "2-4 days",
      returnPolicy: "7-day return",
    },
    {
      id: "6",
      title: "H&M Basic T-Shirt",
      description: "Everyday essential cotton t-shirt with crew neck.",
      brand: "H&M",
      category: "T-Shirts",
      price: 499,
      currency: "INR",
      discountPercentage: 20,
      images: ["https://via.placeholder.com/300"],
      availableColors: ["#CCCCCC", "#000000"],
      availableSizes: ["S", "M", "L", "XL"],
      material: "Cotton",
      fit: "Relaxed",
      style: "Basic",
      rating: 3.9,
      totalReviews: 45,
      seller: "H&M India",
      deliveryTime: "3-5 days",
      returnPolicy: "10-day return",
    },
  ],
  addProduct: (product) =>
    set((state) => ({ products: [...state.products, product] })),
  removeProduct: (id) =>
    set((state) => ({
      products: state.products.filter((p) => p.id !== id),
    })),
}));
