import json


async def gpt_request(client, img, filename, prompt):
    images = [
        [img, filename],
    ]
    response = await client.chat.completions.create(
        [{"content": prompt, "role": "user"}], "", images=images)
    response = response.choices[0].message.content

    response = response.lstrip("```json").rstrip("```")
    if "Generated by BLACKBOX.AI, try unlimited chat https://www.blackbox.ai" in response:
        response = response.replace(
            "Generated by BLACKBOX.AI, try unlimited chat https://www.blackbox.ai", "").strip()
    return json.loads(response)
