import json


prompt = """
Provided below is the image of clothing article, you need to give me the color, type, and tags in the following format as plain-text:
{\"color\" : <the color of the clothing>, \"clothingType\": <the type of the clothing>, \"Tags\": {<generate an array of tags describing the clothing article along with the occasion of the clothing article>}}
The 'type' must fall under the following categories:
upper, lower, full, shoe, accessories, others

Don't generate less than 5 Tags and no more than 7

Except 'Tags' nothing else will be an array
"""


async def gpt_request(client, img, filename):
    images = [
        [img, filename],
    ]
    response = await client.chat.completions.create(
        [{"content": prompt, "role": "user"}], "", images=images)
    response = response.choices[0].message.content

    response = response.lstrip("```json").rstrip("```")
    if "Generated by BLACKBOX.AI, try unlimited chat https://www.blackbox.ai" in response:
        response = response.replace(
            "Generated by BLACKBOX.AI, try unlimited chat https://www.blackbox.ai", "").strip()
    return json.loads(response)
