import json


async def gpt_request(client, img, filename, prompt, body=None):
    images = [
        [img, filename],
    ] if img else None
    messages = [{"content": prompt, "role": "system"}]
    if body:
        messages.append({"content": body, "role": "user"})
    response = await client.chat.completions.create(
        messages,
        model="deepseek-v3",
        images=images,
    )
    response = response.choices[0].message.content

    response = response.lstrip("```json").rstrip("```")
    if "Generated by BLACKBOX.AI, try unlimited chat https://www.blackbox.ai" in response:
        response = response.replace(
            "Generated by BLACKBOX.AI, try unlimited chat https://www.blackbox.ai", "").strip()
    return json.loads(response)


async def create_combinations(client, prompt, body):
    response = await gpt_request(client, img=None, filename=None, prompt=prompt, body=body)
    response = [json.dumps(r) for r in response]
    response = set(response)
    response = list(response)
    response = [json.loads(r) for r in response]
    return response
