import json


async def gpt_request(client, img, filename, prompt):
    images = [
        [img, filename],
    ] if img else None
    response = await client.chat.completions.create(
        [{"content": prompt, "role": "user"}], 
        model="gpt-4o-mini",
        images=images,
        )
    response = response.choices[0].message.content

    response = response.lstrip("```json").rstrip("```")
    if "Generated by BLACKBOX.AI, try unlimited chat https://www.blackbox.ai" in response:
        response = response.replace(
            "Generated by BLACKBOX.AI, try unlimited chat https://www.blackbox.ai", "").strip()
    return json.loads(response)


async def create_combinations(client, prompt):
    response = await client.chat.completions.create(
        [{"content": prompt, "role": "user"}], "", )
    response = response.choices[0].message.content

    response = response.lstrip("```json").rstrip("```")
    if "Generated by BLACKBOX.AI, try unlimited chat https://www.blackbox.ai" in response:
        response = response.replace(
            "Generated by BLACKBOX.AI, try unlimited chat https://www.blackbox.ai", "").strip()

    response = json.loads(response)
    response = [json.dumps(r) for r in response]
    response = set(response)
    response = list(response)
    response = [json.loads(r) for r in response]
    return response
